/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Statue(props) {
  const { nodes, materials } = useGLTF('/glbs/statue.glb')
  console.log(nodes);
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.marble_bust_01.geometry} material={materials.marble_bust_01} position={[0, 0.03, 0]} />
    </group>
  )
}

useGLTF.preload('/glbs/statue.glb')
