/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    marble_bust_01: THREE.Mesh
  }
  materials: {
    marble_bust_01: THREE.MeshStandardMaterial
  }
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/statue.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.marble_bust_01.geometry} material={materials.marble_bust_01} position={[0, 0.03, 0]} />
    </group>
  )
}

useGLTF.preload('/statue.glb')
