import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.scss";
import { useRef, useEffect } from "react";
import { getPositions } from "../components/singleComponents/Utils/Utils";

const Home: NextPage = () => {
  const fwdRef = useRef<HTMLHeadingElement>(null);
  return (
    <div className={styles.container}>
      <Head>
        <title>WEBGL EXPLORATION | ANIMATING SHAPES</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/psyFav.gif" />
      </Head>

      <main className={styles.main}>
        <h2 ref={fwdRef}>WEBGL EXPLORATION | ANIMATING SHAPES</h2>
      </main>
    </div>
  );
};

export default Home;
